config/routes.rb
Rails.application.routes.draw do
  resources :articles #Rails asume que hay un controlador para articles 
  #CUANDO SE CREA EL CONTROLADOR CON LOS METODOS TAMBIEN SE CREAN LAS RUTAS A ESOS METODOS
  get 'articles/index'
  post 'articles/create' 
  get 'articles/edit'
  put 'articles/update'
  get 'articles/show'
  delete 'articles/delete'
  get 'articles/new'

  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    #LAS VALIDACIONES DE LOS DATOS VAN EN EL MODELO
    validates :title, presence: true #Valida que el elemento exista (no esté vacío)
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #AQUI ESTÁ LA LOGICA DEL FRAMEWORK. TODOS LOS CONTROLADORES HEREDAN DE AQUÍ
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #TODOS LOS CONTROLADORES DEBEN TENER ALGUNO O TODOS ESTOS METODOS
  # INDEX -> get
  # CREATE -> post
  # DELETE -> delete
  # SHOW -> get
  # NEW -> get
  # EDIT -> get
  # UPDATE -> patch o put

  #GET y /article
  def index 
    @articles = Article.all #METODO ALL: TODOS LOS REGISTROS DE LA TABLA ARTICLE
    # LAS VARIABLES CON @ SE PUEDEN ACCEDER DESDE LA VISTA Y DESDE EL CONTROLADOR (VARIABLES DE CLASE)
  end

  #POST con /article
  def create #SE PONE EL OBJETO (:article)) Y DESPUES EL ATRIBUTO (:title o :body)
    @article= Article.new(title: params[:article][:title], body: params[:article][:body]) #CON ESTO SE CREA EL OBJETO, PARA GUARDARLOE SE USA SAVE
                        #LOS PARAMETROS QUE ENVIAMOS EN UN FORMULARIO O URL SE ACCEDEN CON UN PARAM
    if @article.save
      redirect_to "/articles" #SE PUEDE PONER @articles PARA QUE ME REDIRECCIONE AL METODO SHOW CON EL ARTICULO QUE ACABO DE CREAR
      # O PUEDO PONER UNA DIRECCION EN ESPECÍFICO CON ""
    else
      render :new #SI NO SE GUARDA, VOLVER A NEW
    end
  end

  def edit
  end

  def update
  end

  #GET article/:id (SE LLAMA CON LA DIRECCION article Y EL NUMERO DEL ID)
  def show 
    @article = Article.find(params[:id]) #PARAMS TIENE TODOS LOS PARAMETROS O ATRIBUTOS DEL ARTICULO
  end

  def delete
  end
  
  #CREA UN NUEVO ARTICULO, PERO NO LO GUARDA EN LA BD SOLO EN MEMORIA
  #PARA CONCRETAR EL GUARDADO SE USA EL METODO CREATE (POST)
  #GET y /articles/new
  def new
    @article = Article.new()
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
<div class = "container"> <!--AQUI LE DOY ESTILO EN LAS STYLESHEETS-->
    <%@articles.each do |article|%> <!-- DESPLEGAR CADA ARTÍCULO --> 
            <div class = "row">
                <div class = "col col-6">
                    <h1><%=article.title%></h1>     
                    <h5><%=article.body%></h5>
                </div>
            </div> 
    <%end%>
    <%= link_to  "Regresar", welcome_index_path, class:"btn btn-primary" %>
 </div>

app/views/articles/new.html.erb
<div class = "container d-flex align-items-center flex-column m-4">
    <h1>CREAR UN NUEVO ARTÍCULO</h1>
    <%= form_for(@article) do |f| %> <!-- CREA UN FORMULARIO PARA LA VARIABLE @articles -->
    <!--SI EL ARTICULO NO SE GUARDO POR LAS VALIDACIONES, SE GENERA UN ATRIBUTO ERRORS-->
        <%@article.errors.each do |value, message|%> <!--EL ERROR TIENE UN VALOR Y UN MENSAJE (EL VALOR QUE TIENE EL ERROR Y EL MENSAJE DE ERROR)-->
            <p><%=message%></p> <!-- DESPLEGAR LOS MENSAJES DE ERROR QUE SE GENERARON ANTERIORMENTE-->
        <%end%>
        <div class = "field">
            <%= f.text_field :title, placeholder: "Título", class:"form-control m-4" %> <!-- PRIMERO SE PONE EL NOMBRE DEL ATRIBUTO EN LA BASE Y DESPUES SE PONEN ATRIBUTOS HTML-->
        </div>
        <div class = "field">
            <%= f.text_area :body, placeholder: "Cuerpo",class:"form-control m-4 " %> <!-- PRIMERO SE PONE EL NOMBRE DEL ATRIBUTO EN LA BASE -->
        </div>
        <div class = "field">
            <%= f.submit "Guardar", class:"btn btn-primary m-2" %> <!-- PRIMERO SE PONE EL NOMBRE DEL ATRIBUTO EN LA BASE -->
        </div>
        <%= link_to  "Regresar", welcome_index_path, class:"btn btn-primary m-2" %>
    <% end %> 
</div>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>
<div class = "container">
    <h2><%=@article.title%></h2>
    <h5><%=@article.body%></h5>
    <%= link_to  "Regresar", welcome_index_path, class:"btn btn-primary" %>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/_navbar.erb
<!-- PARTIAL. PARTE DE CODIGO PARA AGREGAR AL LAYOUT CON UN RENDER -->
 <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand">My First Blog</a>
    <%if user_signed_in? %>
        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-primary", confirm: "JEJEJ VA?" %>
    <%else%>
        <div>
            <%= link_to "Registrarse", new_user_registration_path, class: "btn btn-primary"%>
            <%= link_to "Ingresar", new_user_session_path, class: "btn btn-primary" %>
        <div>
    <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/welcome/index.html.erb
<!-- AQUI SE PUEDE INGRESAR CODIGO HTML Y RUBY EMBEBIDO, USANDO <%%> O <%=%> (PARA IMPRIMIR)-->
<%if user_signed_in?%>
    <h2>Hola <%= current_user.email %>!</h2>
<%else%>
    <h2>Hola! Inicia sesion pls</h2>
<%end%>
<% [1,2,3,4].each do |num| %> <!-- METODO DE RUBY USANDO <%%> PARA PONERLO EN HTML. DENTRO PUSE <%=%> PARA DESPLEGAR LO DEL METODO-->
    <br>
    <%="NUMERO #{num} "%>
<%end #DENTRO DEL CICLO ^ SE PONE LO QUE QUERAMOS HACER%>

<h3>RUTA -> Welcome#index</h3>
<%= link_to  "AGREGAR ARTICULO", articles_new_path, class:"btn btn-primary"%>
<%= link_to  "VER ARTÍCULOS REGISTRADOS", articles_path, class:"btn btn-primary" %>